
.PHONY: all clean

all:
	make -C blink all
	make -C chase all
	make -C echo all
	make -C mandelbrot all

clean:
	make -C blink clean
	make -C chase clean
	make -C echo clean
	make -C mandelbrot clean
